
name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY}}

    - name: Add EC2 to known hosts
      run: ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    - name: Backup .env file
      run: |
        ssh ubuntu@${{ secrets.EC2_IP }} "if [ -f ~/actions-runner/_work/Website/Website/.env ]; then
          cp ~/actions-runner/_work/Website/Website/.env ~/actions-runner/_work/Website/Website/.env.backup
        fi"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    - name: Restore .env file
      run: |
        ssh ubuntu@${{ secrets.EC2_IP }} "mv ~/actions-runner/_work/Website/Website/.env.backup ~/actions-runner/_work/Website/Website/.env"

    - run: pm2 restart app.js
